name: nabe

on:
  schedule:
    - cron: '0 12 * * Fri'
  workflow_dispatch:

jobs:
  nabe:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Private Repo
        env:
          PAT_GITHUB: ${{ secrets.PAT_GITHUB }}
        run: |
          git clone https://x-access-token:${PAT_GITHUB}@github.com/iamCristYE/noginabe.git
          cd noginabe

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8' # Specify the Python version you need
    
      - name: Run apt and pip
        run: |
          sudo apt update
          pip install requests

      - name: Run Python script
        run: |
          cd noginabe
          python nabe.py

      - name: Commit and Push Changes
        run: |
          cd noginabe
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add result.json
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Update sent IDs - $(date)"
            git push
            echo "Changes committed and pushed."
          else
            echo "No changes to commit."
          fi
